#!/bin/bash

# BEFORE SLEEP (category_id = 7)
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Reading","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Caffeine after 4pm","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Supplement","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Relaxation","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Out Late","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Working Late","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Screen Time","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Meditation","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Stressed","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Anxious","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Shower or Bath","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Alcohol","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Food","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Journaling","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Nap during day","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Illness","category_id":7}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Pain / Discomfort","category_id":7}'


# MORNING CHECK IN (category_id = 8)
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Bathroom","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Interrupted Sleep","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Fell Asleep Quickly","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Restful Sleep","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Restless Mind","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Insomnia","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Not Tired","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Sleep Music","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Sleep Stories","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Woke up Refreshed","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Woke up Early","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Woke up Late","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Dreaming","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Noise","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Nightmare","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Cool Room","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Warm Room","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Health Condition","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Pain","category_id":8}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Tossing & Turning","category_id":8}'


# HEADACHES (category_id = 9)
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Migraine","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Headache","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Front Left","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Front Right","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Centre","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Back Left","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Back Right","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Jaw Left Side","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Jaw Right Side","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Dizzy","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Blurred Vision","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Brain Fog","category_id":9}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Pressure in Head","category_id":9}'


# HEALTH (category_id = 10)
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Anxious / Anxiety / Shaking","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Legs Aching","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Fatigue / Ache","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"No Energy","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Skin Peeling on Hands","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Left Shoulder / Arm / Neck Pain","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Right Shoulder / Arm / Neck Pain","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Back Pain – Lower","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Peak Flow test Logged","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Wheezy / Short of breath","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Cold / Flu","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Ear Ache / Humming Left","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Ear Ache / Humming Right","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Acid Reflux Feeling","category_id":10}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Allergy / Hayfever","category_id":10}'


# LIFESTYLE (category_id = 11)
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"DIY Gardening","category_id":11}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Workout","category_id":11}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Cycling","category_id":11}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Walk","category_id":11}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Exercise","category_id":11}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Run","category_id":11}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Gardening","category_id":11}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Acupuncture","category_id":11}'
curl -X POST http://localhost:8000/activities/ -H "Content-Type: application/json" -d '{"name":"Physio","category_id":11}'
