services:
  db:
    image: postgres:15
    container_name: sleep_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sleepnet

  backend:
    build: ./backend
    container_name: sleep_backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    networks:
      - sleepnet

  frontend:
    build: ./frontend
    container_name: sleep_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - sleepnet

networks:
  sleepnet:
    driver: bridge

volumes:
  db_data:
